### ISSUE TITLE
Version 3.3 broke selfupdate leaving script broken on all installs

### ISSUE THREAD

**Issue by doonze** [doonze/EmbyUpdate#10]
There was a critical bug in version 3.3 that broke the auto self updater, you will need to download and install version 3.6 or higher over your existing install (or do a fresh install) to fix!!! Sorry!!

Long story short, an untested and unintended change in a pull request got merged into the master branch, and it broke every single auto-updating instance of EmbyUpdate that ran during the time frame until I became aware of the bug and rolled a fix. This was my fault as I thought I could install (and had) just some parts of the pull request, but instead parts I have not tested yet got into the master branch and I rolled out a new version without being aware. 

This was my first time merging in a pull request, so it's been a learning experience. Sorry for all the inconvenience.

**Comment by MaDTaZ** [comment]
Hey @doonze 
Figured it out the website for emby didnt release the deb for .18

I am getting this error when auto updating I am running 3.6 looking at the website I dont see 18 for download.  

<11/15/21 15:54:33> EmbyUpdate: Most recent online version is 4.7.0.18-Beta and current installed version is 4.7.0.17-Beta. We're updating Emby.

<11/15/21 15:54:33> EmbyUpdate: Starting update......
Starting Package download...
Download failed!! Exiting!

python3 embyupdate.py --version
EmbyUpdate 3.6

I have the new version so it should come back as it was up today?

**Comment by doonze** [comment]
So it was failing because the JSON was showing a new version? But the deb wasn't available for download yet? It will keep trying every run of the script till the deb is available. If that was what the issue was. Sorry for the late response, I was having medical issues and just now got back to where I could look into this. 

Let me know if you're still seeing issues.

**Comment by doonze** [comment]
After looking at my own logs, the new stable release of 4.6.6.0 on the 17th was also messed up. The deb file was not an actual deb file, it was corrupted or something. It tried again on the 18th, and the file issue was corrected and it installed fine. 

Luke is normally on the ball, and these are the first real issues I've had like this since writing the script. I suspect there have been some admin issues on his last few releases, both beta and stable. No surprise really when you consider the number of assets in each of these releases. 129 install files in beta, 88 in stable. There are bound to be misses and bad files from time to time. But Luke is great at getting things like that corrected!

If you read through the code, you'll notice all that changes in the file formats from release to release is the version #, so I have to hard code the file name, changing only the releases number. I have to do this since the releases JSON just lists all 88 (or 128) files without tagging OS in any way. I asked Luke years ago to make sure he never changed the file format as that would break the updater, and he hasn't. But sometimes I think changes get missed. They do get caught quickly and corrected tho.

**Comment by MaDTaZ** [comment]
Ya when I talked to Luke he said they have been having issues with the .net framework that they are moving to.   He said after the first framework has been done we should see less of an issue.

**Comment by doonze** [comment]
Closing as old news now. I broke this a LONG time ago. Let's forget about it, and see what I broke in 4.12.
