### ISSUE TITLE
FR: zypper auto install

### ISSUE THREAD

**Issue by mgaulton** [doonze/EmbyUpdate#17]
Hi There, 
I noticed that when the package is downloaded on Opensuse x64, I have to acknowledge installing the packacage and the unsigned header. There are command line switches to bypass this. Could this be put into the script?

Thank you.

**Comment by doonze** [comment]
Yes, if you provide the syntax, I can update the script no problem. I don't use a distro that uses zypper, the current command came directly from Emby install instructions.

**Comment by doonze** [comment]
Didn't mean to close, clicked wrong button

**Comment by doonze** [comment]
Never heard back, I'd still like to work with someone on the commands needed. I'm happy to update the scripts.
