### ISSUE TITLE
Error on update Opensuse Tumbleweed x64

### ISSUE THREAD

**Issue by mgaulton** [doonze/EmbyUpdate#18]
Currently getting an error of missing dependecies.  Added two rpms that seemed to be what it was looking for, up didn't work.
`
server6:~ # sudo zypper install https://github.com/MediaBrowser/Emby.Releases/releases/download/4.8.0.7/emby-server-rpm_4.8.0.7_x86_64.rpm
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides 'libSPIRV-Tools.so()(64bit)' needed by the to be installed emby-server-4.8.0.7-1.x86_64
 Solution 1: do not install emby-server-4.8.0.7-1.x86_64
 Solution 2: break emby-server-4.8.0.7-1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c):
`

`server6:~ # zypper se spirv
Loading repository data...
Reading installed packages...

S  | Name                               | Summary                                                | Type
---+------------------------------------+--------------------------------------------------------+--------
i+ | libspirv-cross-c-shared0           | Library for SPIR-V reflection and disassembly          | package
i+ | libSPIRV-Tools-2022_3_sdk216       | SPIR-V tool component library                          | package
   | libSPIRV-Tools-2022_3_sdk216-32bit | SPIR-V tool component library                          | package
   | spirv-cross                        | Tool and library for SPIR-V reflection and disassembly | package
   | spirv-cross-devel                  | Development headers for the SPIRV-Cross library        | package
   | spirv-headers                      | Machine-readable files from the SPIR-V registry        | package
   | spirv-tools                        | API and commands for processing SPIR-V modules         | package
   | spirv-tools-devel                  | Development headers for the SPIR-V tool library        | package
   | spirv-tools-devel-32bit            | Development headers for the SPIR-V tool library        | package
`

**Comment by doonze** [comment]
Unfortunately, this doesn't seem to be a script error, but instead an error with the emby package itself. Best course of action would be to post over on the emby fourm and see if anyone has any suggestions. 

But I have some questions. Have you been able to install in before without the script? If you follow the manual install instructions from the Emby fourm does that work?

**Comment by mgaulton** [comment]
sudo zypper --non-interactive install --allow-unsigned-rpm  https://github.com/MediaBrowser/Emby.Releases/releases/download/4.7.8.0/emby-server-rpm_4.7.8.0_x86_64.rpm

**Comment by doonze** [comment]
Closing this issue. Never heard back. If anyone else see this let me know if I need to update the way it installs on Opensuse.

**Comment by doonze** [comment]
Closed
