### ISSUE TITLE
Fedora Server failing update

### ISSUE THREAD

**Issue by agottschling** [doonze/EmbyUpdate#4]
On Fedora Server 32, the script is failing when launched from Systemd with "Download Failed! Exiting". When I execute manually, it's stopping at dnf's prompt to accept the install request. Maybe it needs some updating?
EDIT: Looking at the script, you're not telling dnf to assume yes for the package. Maybe add -y to the script line for Fedora (and anything else that uses dnf)?

**Comment by doonze** [comment]
Good call. Can you add -y to the script and confirm it works? If so, I'll get it added to the code! I only run Debian machines so can't test in other systems. One day I suppose I should spool up some VM's, but I never seem to have the time. Thanks!

**Comment by agottschling** [comment]
Tested on my end. Adding -y towards the beginning makes it work flawlessly.

Cheers!


On Mon, Sep 28, 2020 at 11:18am, doonze < notifications@github.com [notifications@github.com] > wrote:


Good call. Can you add -y to the script and confirm it works? If so, I'll get it added to the code! I only run Debian machines so can't test in other systems. One day I suppose I should spool up some VM's, but I never seem to have the time. Thanks!

**Comment by agottschling** [comment]
So, that would make the command 
```
dnf -y install https://github.com/MediaBrowser/Emby.Releases/releases/download/" + onlineversion + "/emby-server-rpm_" + onlineversion + "_x86_64.rpm
```

**Comment by doonze** [comment]
Perfect, I can roll that out tonight if I get a few spare mins. I had
actually thought I'd done that when I originally wrote it, but that was a
few years ago and it might be one of the others.

**Comment by doonze** [comment]
I rolled the changes, and I also updated the other systems that might run into this issue. Debian never asks for confirmation from Emby so while I had thought of this in the past, I didn't see a need. I'm not sure what's different on Fedora that it asks. But it's fixed anyway!

Thanks for dropping the bug request and doing the testing!!!! Greatly appreciated! Let me know if you encounter any issues!
